### ISSUE TITLE
Cannot configure if data is relatively bigger

### ISSUE THREAD

**Issue by bellowswang** [keplergl/kepler.gl-tableau#35]
We have data with around 900K rows and 4 columns in a sheet, and a click on the 'configure' button in the extension does not respond. If we replace the data with a smaller one (with 260K rows), then it's possible to click, and everything would work.
A maybe related question: is it even possible to read data from a database instead of a tableau sheet in the extension? If not, may I know the reason? Thanks.

**Comment by demartsc** [comment]
hi @bellowswang, would agree that if you get around and/or above 500k points with small number of columns you could run into this scenario. This is due to tableau's extension API (not kepler). There is an issue here already we can follow: https://github.com/tableau/extensions-api/issues/357.

If you want to pull directly from a database you could simply embed a web object on your dashboard with an instance of Kepler running off your database. That is not currently on the roadmap for this project. One thing to note with the web object implementation is that you would have to do additional work to mimic the interactivity enabled in this project.

**Comment by johnDance** [comment]
@demartsc, @bellowswang: We have identified a payload size issue with getSummaryDataAsync. We are working on reducing the payload size, and also improve the speed of the command. In addition, we are adding additional parameters so that an extension can ask for only what it is needed. I'll follow up in the linked issue: https://github.com/tableau/extensions-api/issues/357
John

**Comment by demartsc** [comment]
Will be tracked via tableau’s issue, not specific to Kepler.
